services:
  redis:
    image: redis:7-alpine
    container_name: garcom_digital_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "Redis@123"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Redis@123", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  redis_data:
